name: Tests

env:
  php_version: '7.3'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      name:
        description: 'PHP version'
        required: true
        default: '7.3'

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.3
          version: 1

#      - name: Install dependencies
#        run: composer install --prefer-dist --no-progress

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: tests/configuration.xml
          bootstrap: tests/bootstrap.php
#          php_version: 7.3
